config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'about' => 'movies#about'
  resources :movies
  resources :genres, only: :show
  get 'movies/recommended/:placement' => 'movies#recommended'
  root 'movies#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cast_member.rb
class CastMember < ApplicationRecord
  belongs_to :movie
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movies
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :mpaa_rating, :runtime, :poster_image, presence: true
  validates :runtime, numericality: true

  has_many :cast_members
  belongs_to :genre, optional: true

  scope :with_placement, -> (placement) { where(placement: placement) }

  def self.all_mpaa_ratings
    %w(G PG R NR)
  end

  validates :mpaa_rating, inclusion: { in: self.all_mpaa_ratings }

  def runtime_hours
    unless runtime.nil?
      "#{runtime / 60} hrs. #{runtime % 60} min."
    end
  end

  def cast
    cast_members.map { |c| c.name }.join(', ') unless cast_members.nil?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:index, :show]

  def about
  end

  def index
    @movies = Movie.all
  end

  def show
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie, notice: 'Movie was created successfully.'
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @movie.update(movie_params)
      redirect_to @movie, notice: 'Movie was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def recommended
    @placement = params[:placement]
    @movies = Movie.with_placement(@placement)
    render 'index'
  end

  private
    def set_movie
      @movie = Movie.find(params[:id])
    end

    def movie_params
      params.require(:movie).permit(:title, :description, :has_subtitles, :placement, :mpaa_rating, :release_date, :ticket_price, :runtime, :poster_image, :director, :genre_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<%= render 'movies/movie_list', movies: @genre.movies %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flix</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <div class="wrapper clearfix">
        <h1 class="logo">
          <%= link_to '/' do %>
            <%= image_tag 'logo-2x.png', width: 133 %>
          <% end %>
        </h1>
        <%= form_tag '/', method: :get, class: 'search' do %>
          <%= text_field_tag 'keys', nil, type: 'search', placeholder: 'Search' %>
        <% end %>
      </div>
    </header>
    <div class="band">
      <div class="wrapper clearfix">
        <nav class="main">
          <ul>
            <li class="active">
              <a href="/"><span>Movies</span></a>
            </li>
            <li>
              <a href="#"><span>Theaters</span></a>
            </li>
            <li>
              <a href="#"><span>Blog</span></a>
            </li>
            <li class="last">
              <% if user_signed_in? %>
                <%= link_to "<span>Sign Out</span>".html_safe, destroy_user_session_path, method: :delete %>
              <% else %>
                 <%= link_to "<span>Sign In</span>".html_safe, new_user_session_path %>
              <% end %>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <div id="main">
      <div class="wrapper">
        <div class="inset-block">

        <% if flash[:alert] %>
          <div id="flash" class="alert"><%= flash[:alert] %></div>
        <% elsif flash[:notice] %>
          <div id="flash" class="notice"><%= flash[:notice] %></div>
        <% end %>

          <%= yield %>

        </div>
      </div>
    </div>
    <footer>
      <div class="band band-reverse">
        <div class="wrapper clearfix">
          <div class="clearfix">
            <div class="imgLeft">
              <h2 class="logo logo-small">
              <%= link_to '/' do %>
                <%= image_tag 'logo-small-2x.png', width: 81 %>
              <% end %>
              </h2>
            </div>
            <div class="clearfix">
              <div class="footer-links">
                <div>
                  <a href="/about">About FLIX</a>
                  <span class="sep">|</span>
                  <a href="#">Feedback</a>
                </div>
                <div>
                  <a href="#">Privacy</a>
                  <span class="sep">|</span>
                  <a href="#">Terms</a>
                  <span class="sep">|</span>
                  <a href="#">Help</a>
                  <span class="sep">|</span>
                  <a href="#">1-800-FLIX</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="copyright">
        <div class="wrapper clearfix">
          © FLIX MOVIES All Rights Reserved
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/movies/_form.html.erb
<% if @movie.errors.count > 0 %>
  <div id="flash" class="alert">
    <%= @movie.errors.full_messages.collect { |msg| msg }.join("<br>").html_safe %>
  </div>
<% end %>
<%= form_with model: @movie do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description, cols: 60, rows: 10 %>
  </p>
  <p>
    <%= f.label :genre_id, "Genre" %>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: true %>
  </p>
  <p>
    <%= f.label :has_subtitles %>
    <%= f.check_box :has_subtitles %>
  </p>
  <p>
    <%= f.label :director %>
    <%= f.text_field :director %>
  </p>
  <p>
  <%= f.label :placement %>
    <%= f.radio_button :placement, 'in_theaters' %>
    <%= f.label :placement_in_theaters, "In Theaters" %>
    <%= f.radio_button :placement, 'coming_soon' %>
    <%= f.label :placement_coming_soon, "Coming Soon" %>
    <%= f.radio_button :placement, 'go_now' %>
    <%= f.label :placement_go_now, "Go Now" %>
  </p>
  <p>
    <% mpaa_ratings = options_for_select Movie.all_mpaa_ratings, selected: @movie.mpaa_rating %>
    <%= f.label :mpaa_rating, "MPAA Rating" %>
    <%= f.select :mpaa_rating, mpaa_ratings, include_blank: true %>
  </p>
  <p>
    <%= f.label :release_date %>
    <%= f.date_select :release_date, order: [:month, :day, :year] %>
  </p>
  <p>
    <%= f.label :ticket_price %>
    <%= f.text_field :ticket_price %>
  </p>
  <p>
    <%= f.label :runtime %>
    <%= f.text_field :runtime %>
  </p>
  <p>
    <%= f.label :poster_image %>
    <%= f.text_field :poster_image %>
    <br>
    Please enter the filename of the poster image for this movie.
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/movies/_movie_list.html.erb
<ul class="content-links-list clearfix">
  <% movies.each do |movie| %>
    <li>
      <%= link_to movie_path(movie) do %>
        <div class="clearfix">
          <%= image_tag "posters/thumbs/#{movie.poster_image}", class: 'imgLeft' %>
          <div class="clearfix">
            <h3><%= movie.title %></h3>
            <div><%= movie.cast %></div>
            <div><%= movie.mpaa_rating %>, <%= movie.runtime_hours %></div>
            <div><span class="button">More ›</span></div>
          </div>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/movies/about.html.erb
<h1>About Flix</h1>
<p>Flix is all about movies!</p>

app/views/movies/edit.html.erb
<h1>Edit Movie</h1>
<%= render 'form' %>

app/views/movies/index.html.erb
  <h1>What Movie Do You Want to See?</h1>
  <h3>Find your perfect movie fast with Flix. Get movie showtimes, reviews and more.</h3>
</div>
<div class="tabgroup">
  <nav class="tabs clearfix">
    <ul>
      <li<%= ' class=active' if @placement.nil? %>><%= link_to "All Movies", movies_path %></li>
      <li<%= ' class=active' if @placement == "in_theaters" %>><%= link_to "In Theaters", "/movies/recommended/in_theaters" %><li>
      <li<%= ' class=active' if @placement == "coming_soon" %>><%= link_to "Coming Soon", "/movies/recommended/coming_soon" %><li>
      <li<%= ' class=active' if @placement == "go_now" %>><%= link_to "Go Now", "/movies/recommended/go_now" %><li>
     </ul>
  </nav>
  <div class="clearfix">
    <%= render 'movie_list', movies: @movies %>
    <div class="inset-block">
      <a class="more-movies" href="#">View More Movies</a>
    </div>
  </div>

app/views/movies/new.html.erb
<h1>Add Movie</h1>
<%= render 'form' %>

app/views/movies/show.html.erb
<div id="movie-info" class="clearfix">
  <%= image_tag "posters/large/#{@movie.poster_image}", class: "imgLeft poster-image", alt: "#{@movie.title} poster" %>

  <div class="overview">

    <h2><%= @movie.title %></h2>
    <p>Cast: <%= @movie.cast %></p>
    <p class="mpaa-rating">Rating: <%= @movie.mpaa_rating %></p>
    <p class="runtime">Runtime: <%= @movie.runtime_hours %></p>
    <%= simple_format @movie.description %>
    <%= link_to "Edit This Movie", edit_movie_path(@movie), class: 'button' %>
  </div>
  
  <div class="details">
    <h4>Movie Details</h4>
    <div>
      <span>Genre:</span>
      <%= link_to(@movie.genre.name, @movie.genre) unless @movie.genre.nil? %>
    </div>
    <div>
      <span>Director:</span>
      <%= @movie.director %>
    </div>
    <div>
      <span>Subtitles:</span>
        <% if @movie.has_subtitles? %>   
          Yes
        <% else %>
          No
        <% end %>
    </div>
    <div>
      <span>Ticket Price:</span>
      <%= number_to_currency @movie.ticket_price %>
    </div>
    <div>
      <span>Release Date:</span>
      <%= @movie.release_date.strftime('%-m/%-d/%Y') %>
    </div> 
  </div>
</div>